### ISSUE TITLE
fatal error: stopm holding locks

### ISSUE THREAD

**Issue by icexin** [icexin/eggos#50]
after running `phy` for seconds, panic with output:

``` sh
root@eggos# phy
fatal error: stopm holding locks

runtime stack:
runtime.throw({0x7b7d92, 0x13})
        /Users/fanbingxin/local/go1.17rc1/src/runtime/panic.go:1198 +0x6a
runtime.stopm()
        /Users/fanbingxin/local/go1.17rc1/src/runtime/proc.go:2396 +0xe7
runtime.exitsyscall0(0x50400690)
        /Users/fanbingxin/local/go1.17rc1/src/runtime/proc.go:4115 +0x17a
runtime.mcall()
        /Users/fanbingxin/local/go1.17rc1/src/runtime/asm_386.s:331 +0x44

goroutine 1 [runnable]:
github.com/golang/freetype/raster.(*RGBAPainter).Paint(0x50eca570, {0x50543148, 0x3f, 0x40}, 0x0)
        /Users/fanbingxin/go/pkg/mod/github.com/golang/freetype@v0.0.0-20170609003504-e2365dfdc4a0/raster/paint.go:127 +0x3db
github.com/golang/freetype/raster.(*Rasterizer).Rasterize(0x50542000, {0x8cf484, 0x50eca570})
        /Users/fanbingxin/go/pkg/mod/github.com/golang/freetype@v0.0.0-20170609003504-e2365dfdc4a0/raster/raster.go:545 +0x2ae
github.com/fogleman/gg.(*Context).fill(0x5045ed20, {0x8cf484, 0x50eca570})
        /Users/fanbingxin/go/pkg/mod/github.com/fogleman/gg@v1.3.0/context.go:423 +0x1da
github.com/fogleman/gg.(*Context).FillPreserve(0x5045ed20)
        /Users/fanbingxin/go/pkg/mod/github.com/fogleman/gg@v1.3.0/context.go:470 +0x168
github.com/fogleman/gg.(*Context).Fill(0x5045ed20)
        /Users/fanbingxin/go/pkg/mod/github.com/fogleman/gg@v1.3.0/context.go:476 +0x21
github.com/icexin/eggos/app/phy.(*Drawer).DrawCircle(0x5046a7d0, {0x0, 0x0}, 0x400722222222218e, 0x4051800000000000, {0x3f48c8c9, 0x3f52d2d3)
        /Users/fanbingxin/go/src/github.com/icexin/eggos/app/phy/draw.go:58 +0x390
github.com/jakecoffman/cp.DrawShape(0x50485d80, {0x8e382c, 0x5046a7d0})
        /Users/fanbingxin/go/pkg/mod/github.com/jakecoffman/cp@v1.0.0/draw.go:42 +0x311
github.com/jakecoffman/cp.DrawSpace.func1(0x50485d80)
        /Users/fanbingxin/go/pkg/mod/github.com/jakecoffman/cp@v1.0.0/draw.go:163 +0x2f
github.com/jakecoffman/cp.(*BBTree).Each.func1({0x771dc0, 0x5055c680})
        /Users/fanbingxin/go/pkg/mod/github.com/jakecoffman/cp@v1.0.0/bbtree.go:95 +0x33
github.com/jakecoffman/cp.(*HashSet).Each(0x504515f0, 0x51193cd4)
        /Users/fanbingxin/go/pkg/mod/github.com/jakecoffman/cp@v1.0.0/hashset.go:143 +0x5b
github.com/jakecoffman/cp.(*BBTree).Each(0x50518300, 0x50e06c70)
        /Users/fanbingxin/go/pkg/mod/github.com/jakecoffman/cp@v1.0.0/bbtree.go:93 +0x4e
github.com/jakecoffman/cp.DrawSpace(0x5045ec40, {0x8e382c, 0x5046a7d0})
        /Users/fanbingxin/go/pkg/mod/github.com/jakecoffman/cp@v1.0.0/draw.go:162 +0x8b
github.com/icexin/eggos/app/phy.(*Game).Draw(0x5050ae90, 0x5040f968)
        /Users/fanbingxin/go/src/github.com/icexin/eggos/app/phy/game.go:119 +0x47
github.com/icexin/eggos/app/phy.main(0x50451590)
        /Users/fanbingxin/go/src/github.com/icexin/eggos/app/phy/game.go:137 +0x14c
github.com/icexin/eggos/app.Run({0x5051e2b0, 0x3}, 0x50451590)
        /Users/fanbingxin/go/src/github.com/icexin/eggos/app/app.go:44 +0x8c
github.com/icexin/eggos/app/sh.runApp(0x505d0000, {0x5051e2b0, 0x3}, {0x5050ae80, 0x0, 0x0}, 0x0)
        /Users/fanbingxin/go/src/github.com/icexin/eggos/app/sh/sh.go:67 +0x1c3
github.com/icexin/eggos/app/sh.doline(0x505d0000, {0x5051e298, 0x3})
        /Users/fanbingxin/go/src/github.com/icexin/eggos/app/sh/sh.go:50 +0xc9
github.com/icexin/eggos/app/sh.main(0x505d0000)
        /Users/fanbingxin/go/src/github.com/icexin/eggos/app/sh/sh.go:30 +0x144
github.com/icexin/eggos/app/sh.Bootstrap()
        /Users/fanbingxin/go/src/github.com/icexin/eggos/app/sh/sh.go:80 +0x1fc
main.main()
        /Users/fanbingxin/go/src/github.com/icexin/eggos/kmain/main.go:48 +0x481

goroutine 6 [syscall, locked to thread]:
syscall.Syscall(0x1f4, 0x0, 0x0, 0x0)
        /Users/fanbingxin/local/go1.17rc1/src/syscall/asm_linux_386.s:19 +0x5
github.com/icexin/eggos/kernel.traploop()
        /Users/fanbingxin/go/src/github.com/icexin/eggos/kernel/trap.go:188 +0x11d
created by github.com/icexin/eggos/kernel.Init
        /Users/fanbingxin/go/src/github.com/icexin/eggos/kernel/postinit.go:9 +0x35

goroutine 7 [runnable, locked to thread]:
syscall.Syscall(0x1f5, 0x0, 0x0, 0x0)
        /Users/fanbingxin/local/go1.17rc1/src/syscall/asm_linux_386.s:19 +0x5
github.com/icexin/eggos/kernel.handleForward()
        /Users/fanbingxin/go/src/github.com/icexin/eggos/kernel/syscall.go:330 +0x124
created by github.com/icexin/eggos/kernel.Init
        /Users/fanbingxin/go/src/github.com/icexin/eggos/kernel/postinit.go:10 +0x4b

goroutine 8 [select]:
gvisor.dev/gvisor/pkg/sync.Gopark(...)
        /Users/fanbingxin/go/pkg/mod/gvisor.dev/gvisor@v0.0.0-20210716193733-566c23a60eea/pkg/sync/runtime_unsafe.go:27
gvisor.dev/gvisor/pkg/sleep.(*Sleeper).nextWaker(0x504f8610, 0x1)
        /Users/fanbingxin/go/pkg/mod/gvisor.dev/gvisor@v0.0.0-20210716193733-566c23a60eea/pkg/sleep/sleep_unsafe.go:181 +0x75
gvisor.dev/gvisor/pkg/sleep.(*Sleeper).Fetch(0x504f8610, 0x1)
        /Users/fanbingxin/go/pkg/mod/gvisor.dev/gvisor@v0.0.0-20210716193733-566c23a60eea/pkg/sleep/sleep_unsafe.go:228 +0x2a
gvisor.dev/gvisor/pkg/tcpip/transport/tcp.(*processor).start(0x504f8600, 0x504924f4)
        /Users/fanbingxin/go/pkg/mod/gvisor.dev/gvisor@v0.0.0-20210716193733-566c23a60eea/pkg/tcpip/transport/tcp/dispatcher.go:97 +0x7d
created by gvisor.dev/gvisor/pkg/tcpip/transport/tcp.(*dispatcher).init
        /Users/fanbingxin/go/pkg/mod/gvisor.dev/gvisor@v0.0.0-20210716193733-566c23a60eea/pkg/tcpip/transport/tcp/dispatcher.go:163 +0x142

goroutine 9 [select]:
gvisor.dev/gvisor/pkg/sync.Gopark(...)
        /Users/fanbingxin/go/pkg/mod/gvisor.dev/gvisor@v0.0.0-20210716193733-566c23a60eea/pkg/sync/runtime_unsafe.go:27
gvisor.dev/gvisor/pkg/sleep.(*Sleeper).nextWaker(0x504f8650, 0x1)
        /Users/fanbingxin/go/pkg/mod/gvisor.dev/gvisor@v0.0.0-20210716193733-566c23a60eea/pkg/sleep/sleep_unsafe.go:181 +0x75
gvisor.dev/gvisor/pkg/sleep.(*Sleeper).Fetch(0x504f8650, 0x1)
        /Users/fanbingxin/go/pkg/mod/gvisor.dev/gvisor@v0.0.0-20210716193733-566c23a60eea/pkg/sleep/sleep_unsafe.go:228 +0x2a
gvisor.dev/gvisor/pkg/tcpip/transport/tcp.(*processor).start(0x504f8640, 0x504924f4)
        /Users/fanbingxin/go/pkg/mod/gvisor.dev/gvisor@v0.0.0-20210716193733-566c23a60eea/pkg/tcpip/transport/tcp/dispatcher.go:97 +0x7d
created by gvisor.dev/gvisor/pkg/tcpip/transport/tcp.(*dispatcher).init
        /Users/fanbingxin/go/pkg/mod/gvisor.dev/gvisor@v0.0.0-20210716193733-566c23a60eea/pkg/tcpip/transport/tcp/dispatcher.go:163 +0x142

goroutine 10 [select]:
gvisor.dev/gvisor/pkg/sync.Gopark(...)
        /Users/fanbingxin/go/pkg/mod/gvisor.dev/gvisor@v0.0.0-20210716193733-566c23a60eea/pkg/sync/runtime_unsafe.go:27
gvisor.dev/gvisor/pkg/sleep.(*Sleeper).nextWaker(0x504f8690, 0x1)
        /Users/fanbingxin/go/pkg/mod/gvisor.dev/gvisor@v0.0.0-20210716193733-566c23a60eea/pkg/sleep/sleep_unsafe.go:181 +0x75
gvisor.dev/gvisor/pkg/sleep.(*Sleeper).Fetch(0x504f8690, 0x1)
        /Users/fanbingxin/go/pkg/mod/gvisor.dev/gvisor@v0.0.0-20210716193733-566c23a60eea/pkg/sleep/sleep_unsafe.go:228 +0x2a
gvisor.dev/gvisor/pkg/tcpip/transport/tcp.(*processor).start(0x504f8680, 0x504924f4)
        /Users/fanbingxin/go/pkg/mod/gvisor.dev/gvisor@v0.0.0-20210716193733-566c23a60eea/pkg/tcpip/transport/tcp/dispatcher.go:97 +0x7d
created by gvisor.dev/gvisor/pkg/tcpip/transport/tcp.(*dispatcher).init
        /Users/fanbingxin/go/pkg/mod/gvisor.dev/gvisor@v0.0.0-20210716193733-566c23a60eea/pkg/tcpip/transport/tcp/dispatcher.go:163 +0x142

goroutine 11 [select]:
gvisor.dev/gvisor/pkg/sync.Gopark(...)
        /Users/fanbingxin/go/pkg/mod/gvisor.dev/gvisor@v0.0.0-20210716193733-566c23a60eea/pkg/sync/runtime_unsafe.go:27
gvisor.dev/gvisor/pkg/sleep.(*Sleeper).nextWaker(0x504f86d0, 0x1)
        /Users/fanbingxin/go/pkg/mod/gvisor.dev/gvisor@v0.0.0-20210716193733-566c23a60eea/pkg/sleep/sleep_unsafe.go:181 +0x75
gvisor.dev/gvisor/pkg/sleep.(*Sleeper).Fetch(0x504f86d0, 0x1)
        /Users/fanbingxin/go/pkg/mod/gvisor.dev/gvisor@v0.0.0-20210716193733-566c23a60eea/pkg/sleep/sleep_unsafe.go:228 +0x2a
gvisor.dev/gvisor/pkg/tcpip/transport/tcp.(*processor).start(0x504f86c0, 0x504924f4)
        /Users/fanbingxin/go/pkg/mod/gvisor.dev/gvisor@v0.0.0-20210716193733-566c23a60eea/pkg/tcpip/transport/tcp/dispatcher.go:97 +0x7d
created by gvisor.dev/gvisor/pkg/tcpip/transport/tcp.(*dispatcher).init
        /Users/fanbingxin/go/pkg/mod/gvisor.dev/gvisor@v0.0.0-20210716193733-566c23a60eea/pkg/tcpip/transport/tcp/dispatcher.go:163 +0x142

goroutine 12 [select]:
gvisor.dev/gvisor/pkg/sync.Gopark(...)
        /Users/fanbingxin/go/pkg/mod/gvisor.dev/gvisor@v0.0.0-20210716193733-566c23a60eea/pkg/sync/runtime_unsafe.go:27
gvisor.dev/gvisor/pkg/sleep.(*Sleeper).nextWaker(0x504f8710, 0x1)
        /Users/fanbingxin/go/pkg/mod/gvisor.dev/gvisor@v0.0.0-20210716193733-566c23a60eea/pkg/sleep/sleep_unsafe.go:181 +0x75
gvisor.dev/gvisor/pkg/sleep.(*Sleeper).Fetch(0x504f8710, 0x1)
        /Users/fanbingxin/go/pkg/mod/gvisor.dev/gvisor@v0.0.0-20210716193733-566c23a60eea/pkg/sleep/sleep_unsafe.go:228 +0x2a
gvisor.dev/gvisor/pkg/tcpip/transport/tcp.(*processor).start(0x504f8700, 0x504924f4)
        /Users/fanbingxin/go/pkg/mod/gvisor.dev/gvisor@v0.0.0-20210716193733-566c23a60eea/pkg/tcpip/transport/tcp/dispatcher.go:97 +0x7d
created by gvisor.dev/gvisor/pkg/tcpip/transport/tcp.(*dispatcher).init
        /Users/fanbingxin/go/pkg/mod/gvisor.dev/gvisor@v0.0.0-20210716193733-566c23a60eea/pkg/tcpip/transport/tcp/dispatcher.go:163 +0x142

goroutine 13 [select]:
gvisor.dev/gvisor/pkg/sync.Gopark(...)
        /Users/fanbingxin/go/pkg/mod/gvisor.dev/gvisor@v0.0.0-20210716193733-566c23a60eea/pkg/sync/runtime_unsafe.go:27
gvisor.dev/gvisor/pkg/sleep.(*Sleeper).nextWaker(0x504f8750, 0x1)
        /Users/fanbingxin/go/pkg/mod/gvisor.dev/gvisor@v0.0.0-20210716193733-566c23a60eea/pkg/sleep/sleep_unsafe.go:181 +0x75
gvisor.dev/gvisor/pkg/sleep.(*Sleeper).Fetch(0x504f8750, 0x1)
        /Users/fanbingxin/go/pkg/mod/gvisor.dev/gvisor@v0.0.0-20210716193733-566c23a60eea/pkg/sleep/sleep_unsafe.go:228 +0x2a
gvisor.dev/gvisor/pkg/tcpip/transport/tcp.(*processor).start(0x504f8740, 0x504924f4)
        /Users/fanbingxin/go/pkg/mod/gvisor.dev/gvisor@v0.0.0-20210716193733-566c23a60eea/pkg/tcpip/transport/tcp/dispatcher.go:97 +0x7d
created by gvisor.dev/gvisor/pkg/tcpip/transport/tcp.(*dispatcher).init
        /Users/fanbingxin/go/pkg/mod/gvisor.dev/gvisor@v0.0.0-20210716193733-566c23a60eea/pkg/tcpip/transport/tcp/dispatcher.go:163 +0x142

goroutine 14 [select]:
github.com/icexin/eggos/inet/dhcp.(*Client).renewAfter.func1(0x4e94914f0000, {0x8d9ec0, 0x50451560}, 0x5047de00)
        /Users/fanbingxin/go/src/github.com/icexin/eggos/inet/dhcp/client.go:260 +0xcd
created by github.com/icexin/eggos/inet/dhcp.(*Client).renewAfter
        /Users/fanbingxin/go/src/github.com/icexin/eggos/inet/dhcp/client.go:257 +0xdb

goroutine 15 [syscall]:
os/signal.signal_recv()
        /Users/fanbingxin/local/go1.17rc1/src/runtime/sigqueue.go:169 +0xf1
os/signal.loop()
        /Users/fanbingxin/local/go1.17rc1/src/os/signal/signal_unix.go:24 +0x1a
created by os/signal.Notify.func1.1
        /Users/fanbingxin/local/go1.17rc1/src/os/signal/signal.go:151 +0x2f
```

**Comment by icexin** [comment]
go1.13.x is ok

**Comment by mewmew** [comment]
If it builds ok on Go 1.13.x and upwards, perhaps this can be closed?

**Comment by icexin** [comment]
Yes, it has not been reproduced later, this issue can be closed.
